CREATE TABLE products_orders(
    id SERIAL PRIMARY KEY,
    order_id INTEGER REFERENCES Orders(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    product_id INTEGER REFERENCES Products(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    quantity INTEGER)
