CREATE TABLE Products_Orders(
    id SERIAL PRIMARY KEY,
    order_id INTEGER REFERENCES Orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
    product_id INTEGER REFERENCES Products(id) ON UPDATE CASCADE ON DELETE CASCADE,
    quantity INTEGER)
